---
- name: Убедиться, что Docker установлен
  ansible.builtin.apt:
    name: docker.io
    state: present
  tags: docker

- name: Убедиться, что Docker Compose установлен
  ansible.builtin.apt:
    name: docker-compose
    state: present
  tags: docker_compose

- name: Копировать docker-compose.yml на сервер
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
  tags: deploy

- name: Генерировать конфигурацию Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /home/{{ ansible_user }}/nginx.conf
  notify: restart nginx
  tags: nginx

- name: Запустить Docker Compose
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: /home/{{ ansible_user }}
  tags: deploy
